# Generated by Django 6.0.2 on 2026-02-21 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_rows', models.IntegerField(default=0)),
                ('anomaly_count', models.IntegerField(default=0)),
                ('anomaly_records', models.JSONField(default=list)),
                ('summary_stats', models.JSONField(default=dict)),
                ('column_names', models.JSONField(default=list)),
                ('numerical_columns', models.JSONField(default=list)),
                ('text_columns', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='core.uploadedreport')),
            ],
            options={
                'verbose_name': 'Anomaly Result',
                'verbose_name_plural': 'Anomaly Results',
            },
        ),
        migrations.CreateModel(
            name='ResultFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='results/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result_file', to='reports.anomalyresult')),
            ],
        ),
    ]
